<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RESTClient\RESTClient.csproj" />
    <ProjectReference Include="..\REST_TEST.csproj" />
  </ItemGroup>

</Project>
